import matplotlib.pyplot as plt
import numpy as np
from scipy.interpolate import make_interp_spline
from matplotlib.ticker import FormatStrFormatter
from mpl_toolkits.axes_grid1.inset_locator import inset_axes
def grafikamega(x,c,roa,rop,tm,tau,nn):

    #c grafigi
    fig =plt.figure(figsize=(6, 3))
    plt.style.use('classic')
    ax = plt.subplot(111)
    ax.plot(x[:nn],c[:nn,(tm-1)//3],'b--',label='$t=3000  \: s$',lw=2)
    ax.plot(x[:nn],c[:nn,2*(tm-1)//3],'r-.',label='$t=6000  \: s$',lw=2)
    ax.plot(x[:nn],c[:nn,3*(tm-1)//3],'g:',label='$t=9000  \: s$',lw=2)
    ax.spines['right'].set_visible(False)
    ax.spines['top'].set_visible(False)
    ax.yaxis.set_ticks_position('left')
    ax.xaxis.set_ticks_position('bottom')
    plt.legend()
    ax.text(0.0, ax.get_ylim()[1]*1.05, "$c/c_0$",fontsize=14)
   # ax.text(ax.get_xlim()[1]*1.01, 0.0, "$x, m$", fontsize=14)
    ax.text(ax.get_xlim()[1]/2, ax.get_ylim()[1]*1.05, "$a$",fontsize=14)
    plt.ylim(0.0,1.01)
    plt.yticks(0.2 * np.arange(0, 6, 1))
    plt.xticks(0.1 * np.arange(0, 6, 1))
   
    fig.savefig('cc0.eps')
    fig.savefig('cc0.jpg',dpi=600)
    #plt.figure()

    #ca larni chizish
    fig1 =plt.figure(figsize=(6, 3))
    plt.style.use('classic')
    ax = plt.subplot(111)
    ax.plot(x[:nn],roa[:nn,1*(tm-1)//3],'b--',label='$t=3000  \: s$',lw=2)
    ax.plot(x[:nn],roa[:nn,2*(tm-1)//3],'r-.',label='$t=6000  \: s$',lw=2)
    ax.plot(x[:nn],roa[:nn,3*(tm-1)//3],'g:',label='$t=9000  \: s$',lw=2)
    ax.spines['right'].set_visible(False)
    ax.spines['top'].set_visible(False)
    ax.yaxis.set_ticks_position('left')
    ax.xaxis.set_ticks_position('bottom')
    plt.legend()
    ax.text(0.0, ax.get_ylim()[1]*1.05, "$10^3 \cdot c_a, \u0020 m^3/m^3$",fontsize=14)
    ax.text(ax.get_xlim()[1]*1.01, 0.0, "$x, m$", fontsize=14)
    ax.text(ax.get_xlim()[1]/2, ax.get_ylim()[1]*1.05, "$b$", fontsize=14)
    plt.ylim(0.0,4.05)
    plt.yticks(np.arange(0, 5, 1))
    ax.yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    plt.xticks(0.1 * np.arange(0, 6, 1))
    fig.savefig('roa.eps')
    fig1.savefig('roa.jpg',dpi=600)
    #plt.ylim(0.0,0.0103)

    #cp larni chizish
    fig2 =plt.figure(figsize=(6, 3))
    plt.style.use('classic')
    ax = plt.subplot(111)
    ax.plot(x[:nn],rop[:nn,1*(tm-1)//3],'b--',label='$t=3000  \: s$',lw=2)
    ax.plot(x[:nn],rop[:nn,2*(tm-1)//3],'r-.',label='$t=6000  \: s$',lw=2)
    ax.plot(x[:nn],rop[:nn,3*(tm-1)//3],'g:',label='$t=9000  \: s$',lw=2)
    ax.spines['right'].set_visible(False)
    ax.spines['top'].set_visible(False)
    ax.yaxis.set_ticks_position('left')
    ax.xaxis.set_ticks_position('bottom')
    plt.legend()
    ax.text(0.0, ax.get_ylim()[1]*1.05, "$10^3 \cdot c_p,  \u0020 m^3/m^3$",fontsize=14)
    ax.text(ax.get_xlim()[1]*1.01, 0.0, "$x, m$", fontsize=14)
    ax.text(ax.get_xlim()[1]/2, ax.get_ylim()[1]*1.05, "$c$", fontsize=14)
    plt.ylim(0.0,8.05)
    plt.yticks(np.arange(0, 9, 2))
    ax.yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    plt.xticks(0.1*np.arange(0, 6, 1))

    fig.savefig('rop.eps')
    fig2.savefig('rop.jpg',dpi=600)

#cp1 ning turli qiymatglari
def grafik1_x(x,c,roa,rop,tm,tau,nn):

    #c grafigi
    fig =plt.figure(figsize=(6, 3))
    plt.style.use('classic')
    ax = plt.subplot(111)
    ax.plot(x[:nn],c[:nn,(tm-1)//3],'b--',label='$t=3000  \: s$',lw=2)
    ax.plot(x[:nn],c[:nn,2*(tm-1)//3],'r-.',label='$t=6000  \: s$',lw=2)
    ax.plot(x[:nn],c[:nn,3*(tm-1)//3],'g:',label='$t=9000  \: s$',lw=2)
    ax.spines['right'].set_visible(False)
    ax.spines['top'].set_visible(False)
    ax.yaxis.set_ticks_position('left')
    ax.xaxis.set_ticks_position('bottom')
    plt.legend()
    ax.text(0.0, ax.get_ylim()[1]*1.05, "$c/c_0$",fontsize=14)
   # ax.text(ax.get_xlim()[1]*1.01, 0.0, "$x, m$", fontsize=14)
    ax.text(ax.get_xlim()[1]/2, ax.get_ylim()[1]*1.05, "$a$",fontsize=14)
    plt.ylim(0.0,1.01)
    plt.yticks(0.2 * np.arange(0, 6, 1))
    plt.xticks(0.1 * np.arange(0, 5, 1))
   
    #fig.savefig('cc0.eps')
    fig.savefig('cc0.jpg',dpi=600)
    #plt.figure()

    #ca larni chizish
    fig1 =plt.figure(figsize=(6, 3))
    plt.style.use('classic')
    ax = plt.subplot(111)
    ax.plot(x[:nn],roa[:nn,1*(tm-1)//3],'b--',label='$t=3000  \: s$',lw=2)
    ax.plot(x[:nn],roa[:nn,2*(tm-1)//3],'r-.',label='$t=6000  \: s$',lw=2)
    ax.plot(x[:nn],roa[:nn,3*(tm-1)//3],'g:',label='$t=9000  \: s$',lw=2)
    ax.spines['right'].set_visible(False)
    ax.spines['top'].set_visible(False)
    ax.yaxis.set_ticks_position('left')
    ax.xaxis.set_ticks_position('bottom')
    plt.legend()
    ax.text(0.0, ax.get_ylim()[1]*1.05, "$10^3 \cdot c_a, \u0020 m^3/m^3$",fontsize=14)
    ax.text(ax.get_xlim()[1]*1.01, 0.0, "$x, m$", fontsize=14)
    ax.text(ax.get_xlim()[1]/2, ax.get_ylim()[1]*1.05, "$b$", fontsize=14)
    plt.ylim(0.0,4.05)
    plt.yticks(np.arange(0, 5, 1))
    ax.yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    plt.xticks(0.1 * np.arange(0, 5, 1))
    #fig.savefig('roa.eps')
    fig1.savefig('roa.jpg',dpi=600)
    #plt.ylim(0.0,0.0103)

    #cp larni chizish
    fig2 =plt.figure(figsize=(6, 3))
    plt.style.use('classic')
    ax = plt.subplot(111)
    ax.plot(x[:nn],rop[:nn,1*(tm-1)//3],'b--',label='$t=3000  \: s$',lw=2)
    ax.plot(x[:nn],rop[:nn,2*(tm-1)//3],'r-.',label='$t=6000  \: s$',lw=2)
    ax.plot(x[:nn],rop[:nn,3*(tm-1)//3],'g:',label='$t=9000  \: s$',lw=2)
    ax.spines['right'].set_visible(False)
    ax.spines['top'].set_visible(False)
    ax.yaxis.set_ticks_position('left')
    ax.xaxis.set_ticks_position('bottom')
    plt.legend()
    ax.text(0.0, ax.get_ylim()[1]*1.05, "$10^3 \cdot c_p,  \u0020 m^3/m^3$",fontsize=14)
    ax.text(ax.get_xlim()[1]*1.01, 0.0, "$x, m$", fontsize=14)
    ax.text(ax.get_xlim()[1]/2, ax.get_ylim()[1]*1.05, "$c$", fontsize=14)
    plt.ylim(0.0,8.05)
    plt.yticks(np.arange(0, 9, 2))
    ax.yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    plt.xticks(0.1*np.arange(0, 5, 1))

    #fig.savefig('rop.eps')
    fig2.savefig('rop.jpg',dpi=600)
def grafik1_x_2(x,c,roa,rop,tm,tau,nn):

    #c grafigi
    fig =plt.figure(figsize=(6, 3))
    plt.style.use('classic')
    ax = plt.subplot(111)
    ax.plot(x[:nn],c[:nn,(tm-1)//3],'b--',label='$t=3000  \: s$',lw=2)
    ax.plot(x[:nn],c[:nn,2*(tm-1)//3],'r-.',label='$t=6000  \: s$',lw=2)
    ax.plot(x[:nn],c[:nn,3*(tm-1)//3],'g:',label='$t=9000  \: s$',lw=2)
    ax.spines['right'].set_visible(False)
    ax.spines['top'].set_visible(False)
    ax.yaxis.set_ticks_position('left')
    ax.xaxis.set_ticks_position('bottom')
    plt.legend()
    ax.text(0.0, ax.get_ylim()[1]*1.05, "$c/c_0$",fontsize=14)
   # ax.text(ax.get_xlim()[1]*1.01, 0.0, "$x, m$", fontsize=14)
    ax.text(ax.get_xlim()[1]/2, ax.get_ylim()[1]*1.05, "$a$",fontsize=14)
    plt.ylim(0.0,1.01)
    plt.yticks(0.2 * np.arange(0, 6, 1))
    plt.xticks(0.1 * np.arange(0, 5, 1))
   
    #fig.savefig('cc0.eps')
    fig.savefig('cc0.jpg',dpi=600)
    #plt.figure()

    #ca larni chizish
    fig1 =plt.figure(figsize=(6, 3))
    plt.style.use('classic')
    ax = plt.subplot(111)
    ax.plot(x[:nn],roa[:nn,1*(tm-1)//3],'b--',label='$t=3000  \: s$',lw=2)
    ax.plot(x[:nn],roa[:nn,2*(tm-1)//3],'r-.',label='$t=6000  \: s$',lw=2)
    ax.plot(x[:nn],roa[:nn,3*(tm-1)//3],'g:',label='$t=9000  \: s$',lw=2)
    ax.spines['right'].set_visible(False)
    ax.spines['top'].set_visible(False)
    ax.yaxis.set_ticks_position('left')
    ax.xaxis.set_ticks_position('bottom')
    plt.legend()
    ax.text(0.0, ax.get_ylim()[1]*1.05, "$10^3 \cdot c_a, \u0020 m^3/m^3$",fontsize=14)
    ax.text(ax.get_xlim()[1]*1.01, 0.0, "$x, m$", fontsize=14)
    ax.text(ax.get_xlim()[1]/2, ax.get_ylim()[1]*1.05, "$b$", fontsize=14)
    plt.ylim(0.0,4.05)
    plt.yticks(np.arange(0, 5, 1))
    ax.yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    plt.xticks(0.1 * np.arange(0, 5, 1))
    #fig.savefig('roa.eps')
    fig1.savefig('roa.jpg',dpi=600)
    #plt.ylim(0.0,0.0103)

    #cp larni chizish
    fig2 =plt.figure(figsize=(6, 3))
    plt.style.use('classic')
    ax = plt.subplot(111)
    ax.plot(x[:nn],rop[:nn,1*(tm-1)//3],'b--',label='$t=3000  \: s$',lw=2)
    ax.plot(x[:nn],rop[:nn,2*(tm-1)//3],'r-.',label='$t=6000  \: s$',lw=2)
    ax.plot(x[:nn],rop[:nn,3*(tm-1)//3],'g:',label='$t=9000  \: s$',lw=2)
    ax.spines['right'].set_visible(False)
    ax.spines['top'].set_visible(False)
    ax.yaxis.set_ticks_position('left')
    ax.xaxis.set_ticks_position('bottom')
    plt.legend()
    ax.text(0.0, ax.get_ylim()[1]*1.05, "$10^3 \cdot c_p,  \u0020 m^3/m^3$",fontsize=14)
    ax.text(ax.get_xlim()[1]*1.01, 0.0, "$x, m$", fontsize=14)
    ax.text(ax.get_xlim()[1]/2, ax.get_ylim()[1]*1.05, "$c$", fontsize=14)
    plt.ylim(0.0,8.05)
    plt.yticks(np.arange(0, 9, 2))
    ax.yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    plt.xticks(0.1*np.arange(0, 5, 1))

    #fig.savefig('rop.eps')
    fig2.savefig('rop.jpg',dpi=600)
#cp1 ning turli qiymatglari